name: Aprendiendo Expresiones
run-name: Estoy aprendiendo Expresiones de GitHub

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Nombre'
        required: true
        default: 'Username'
        type: string
      genero:
        description: "Genero"
        required: true
        default: "-"
        type: choice
        options:
        - H
        - M
jobs:
  validar:
    runs-on: ubuntu-latest
    env:
      YEARS: ${{ fromJSON(github.event.inputs.edad) }}
      NAME: ${{ github.event.inputs.nombre }}
      GENRE: ${{ github.event.inputs.genero }}
    steps:
      - name: Mayor de edad y género M
        if: ${{ env.GENRE == 'M' && env.YEARS >= 18 }}
        run: echo "Hola amiga ${{ env.NAME }}, eres mujer y mayor de edad y puedes votar"

      - name: Menor de edad y género M
        if: ${{ env.GENRE == 'M' && env.YEARS >= 0 && env.YEARS < 18 }}
        run: echo "Hola amiga ${{ env.NAME }}, eres mujer y menor de edad no puedes votar"

      - name: Mayor de edad y género H
        if: ${{ env.GENRE == 'H' && env.YEARS >= 18 }}
        run: echo "Hola amigo ${{ env.NAME }}, eres hombre y mayor de edad y puedes votar"

      - name: Menor de edad y género H
        if: ${{ env.GENRE == 'H' && env.YEARS >= 0 && env.YEARS < 18 }}
        run: echo "Hola amig0 ${{ env.NAME }}, eres hombre y menor de edad no puedes votar"

      - name: Mostrar variables JSON
        run: echo '${{ toJSON(env) }}'
